### ISSUE TITLE
Engines was increased to >=8.12.0 in 1.2.1, which is a breaking change

### ISSUE THREAD

**Issue by johannes-scharlach** [hapijs/bounce#11]
as of https://github.com/hapijs/bounce/commit/5ca04397e3dd05b3ae8b0b5798cd86345a3f03cc the minimal required node version is 8.12. I assume this change was made in error, as the commit message is "misc"? Otherwise this is a breaking change – e.g. all users of AWS Lambda are still using node 8.10, so upgrading is not an option for everyone.

EDIT: this is also related to https://github.com/hapijs/boom/issues/207

EDIT2: This is an issue as I'm using `yarn` as my package manager and commands like `yarn install`, `yarn add`, etc. fail with this version of bounce.

I'd prefer if this package would keep the engines version at `>=8.0.0`, so that if I try to install it with node v6 I receive an error, but with node v8.10 I am ok.

**Comment by hueniverse** [comment]
Same as the other issues. See https://github.com/hapijs/hapi/issues/3859.
