### ISSUE TITLE
"For more information" articles no longer exist

### ISSUE THREAD

**Issue by jameswragg** [hapijs/bounce#30]
#### Context

* *node version*: N/A
* *module version*: 2.0.0

#### What are you trying to achieve or the steps to reproduce ?

I'm trying to understand better how to use `@hapi/bounce` by trying to read the linked articles from [API.md](https://github.com/hapijs/bounce/blame/master/API.md#L13) which no longer exist:

```
For more information read:
- [Learning to Throw Again](https://medium.com/@eranhammer/learning-to-throw-again-79b498504d28)
- [Catching without Awaiting](https://medium.com/@eranhammer/catching-without-awaiting-b2cb7df45790)
```

**Comment by Nargonath** [comment]
It seems that Eran deleted them from Medium. I'll reach out to him to check whether they're available somewhere else. Thanks for raising the issue.

**Comment by hueniverse** [comment]
[posts.zip](https://github.com/hapijs/bounce/files/7230737/posts.zip)

**Comment by Nargonath** [comment]
Thanks @hueniverse. 👍
